export type GenerateProjectConfig = {
  projectName: string;
};

export function generateProject(config?: GenerateProjectConfig) {
  const projectName = config?.projectName.trim() || "launchkit-app";

  return {
    "README.md": `# ${projectName}
    
    Generated by LaunchKit 🚀
    `,
  };
}
